version: '3.8'

services:
    seoulair-device:
        container_name: seoulair-device
        restart: always
        image: seoulair-device
        network_mode: bridge
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 5500:5500
        links:
            - "eclipse-mosquitto"

    eclipse-mosquitto:
        container_name: eclipse-mosquitto
        restart: always
        image: eclipse-mosquitto
        network_mode: bridge
        ports:
            - 1883:1883
            - 9001:9001
